### ISSUE TITLE
Ontouml-validator package missing on PyPi ?

### ISSUE THREAD

**Issue by keesnieuwstad** [OntoUML/ontouml-validator#39]
In the README.md file, it is said to use 

`pip install ontouml-validator`

To install the validator.
When i use this, I get the result:

`PS C:\GitRepos\ontouml-validator\validator> pip install ontouml-validator`

`Defaulting to user installation because normal site-packages is not writeable`
`ERROR: Could not find a version that satisfies the requirement ontouml-validator (from versions: none)`
`ERROR: No matching distribution found for ontouml-validator`

When I search on the [Package index](https://pypi.org/search/), I do not get hits on ontouml-validator.

Am I doing wrong? Or is there something wrong with the ontouml-validator package on PyPi?

**Comment by pedropaulofb** [comment]
Hi @keesnieuwstad ! Thank you for your interest. Unfortunately, I could not continue with this project. So it is not functional. My apologies for the lack of clarity regarding that in the repository page.

The OntoUML-related working Python libs I have developed are:
- https://github.com/OntoUML/ontouml-json2graph
- https://github.com/OntoUML/ontouml-models-lib (beta, but functional)
- https://github.com/OntoUML/ontouml-vocabulary-lib

Please let me know if I can help you with something else, ok? It will be a pleasure to help you.
